### ISSUE TITLE
How can I change my 404 page?

### ISSUE THREAD

**Issue by dev-at-bots** [bhadaway/generic-theme#17]
Before I installed this theme, I was using Twenty Twenty-Three, and had created a 404 page (that had a different slug). I would like for my 404 page to be this page, but I can't figure out how to get it to work without it changing the slug to 404-2.

**Comment by bhadaway** [comment]
Are you using a custom 404 page plugin? Check your Pages in the admin to make sure that any other 404 pages, regardless of whether they're published, drafts, or in the trash, are fully deleted out.

**Comment by dev-at-bots** [comment]
Thanks! No, I'm not using a custom 404 plugin.

There are no 404 pages in my admin panel, unless I have activated Twenty Twenty-Three and can access their site editor, which is not available with Generic.

I'm using a child theme of Generic.

I can directly edit the 404.php file found in the Generic theme, which I copied to the child theme.

Oddly enough, I can still access the 404-2 page, even though I trashed and deleted permanently the page I had created to be the 404 page. This is even after clearing my cache.

I'm helping out a non-techy friend, and I'm just a brand-new baby dev who knows a little HTML, CSS, and JavaScript. I'm starting to learn how to dig into WordPress and PHP, so thanks for your patience! I've already gotten answers to a few of my other questions by looking through your answers to past issues.

I'm currently developing locally, so I don't have a live site to share.

**Comment by bhadaway** [comment]
Based on our discussion so far, I'm guessing the block editor allows you to assign a custom page as the 404 page? I prefer classic WordPress, where it's not possible to do that, which is why I assumed it must be a plugin.

So, Generic is a classic theme, which means you can't actually set a custom 404 page; it just uses whatever's in the 404 template. I think there must be some wonkiness created in the database by switching between the two.

The only 2 options I can think of are to either:

A. Install the Classic Editor plugin: https://wordpress.org/plugins/classic-editor/.

or

B. Abandon Generic and try Block Builder: https://wordpress.org/themes/block-builder/ (a minimalist block theme I created, so a kind of compromise between the two).

**Comment by dev-at-bots** [comment]
Oh, thanks! I will install the classic editor plugin and see what kind of trouble I can get myself into. :-)

**Comment by dev-at-bots** [comment]
One other question:  Does PHP modify the DOM like JavaScript does? I'm having trouble with conflict between browser themes (light vs. dark) and the theme theme, if you will. When the browser theme is light, the site title is invisible because it's white, but when I change that manually in style.css, I have the opposite problem when the browser theme is dark.

I'm guessing I don't really want to mix JS with PHP for a WordPress blog, but I don't really know what I don't know. As I said, I'm pretty new to this whole thing, particularly PHP.

**Comment by bhadaway** [comment]
WordPress themes are primarily built with HTML, CSS, PHP, and JS, and it's fine to mix all these together.

PHP does not affect the DOM directly, no. It all happens in the back-end.

This is an oversimplification, but PHP simply outputs HTML based on conditional "if this, then that" statements.

You can probably handle light/dark modes exclusively with CSS in 2023:

Simple: https://css-tricks.com/dark-modes-with-css/
Advanced: https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

**Comment by dev-at-bots** [comment]
Excellent, thanks!
