### ISSUE TITLE
Main menu sub-menus cover everything underneath it

### ISSUE THREAD

**Issue by MediaMaquina** [bhadaway/generic-theme#2]
If you have a menu with sub-menu and hover over it, the sub-items instead of showing up next (right or left) of the main menu shows up above it. hiding every other option under it.

**Comment by bhadaway** [comment]
The third level of the menu structure was intentionally omitted.

Short answer: It's a bad and dated style of menu design; organize your navigation better.

Long answer: https://ux.stackexchange.com/questions/13860/how-to-explain-to-director-that-a-multilevel-dropdown-menu-isnt-a-good-idea

Don't care? I'd still be happy to help you customize it to your liking. Link?

**Comment by MediaMaquina** [comment]
3rd level is a little early to drop support in my opinion.
I bet there are billions of sites with 3rd level options, are they all stupid? I'm not sure.

**Comment by bhadaway** [comment]
It's not stupid, but like I said, dated. That is only my opinion of course.

Generic is merely a starter tool, and therefore gives a hint at features, rather than having full-blown support for every bell and whistle. If you want third-level dropdowns and beyond, you can have them; you can customize the theme code how you like; that's the entire point.

Concerning the issue of the trend of this style, browsing around, looking at the top websites, most have long-abandoned the style in way of other solutions. By far, the most popular style now seems to be multi-column, one-level dropdowns, using CSS: `column-count`.

But, others still use the style you're after:

https://www.xbox.com/
