### ISSUE TITLE
Logo feature

### ISSUE THREAD

**Issue by tesdallm** [bhadaway/generic-theme#4]
Is there a way for me to pull the logo off the generic theme header? With the recent update, my website now says "logo here" and I'd rather it go back to just the title. (novice website manager).

**Comment by bhadaway** [comment]
Since you're using the theme in a way that you'll continue to receive automatic updates, you'll need to use a child theme to make any customizations you want.

I went ahead and prepared one for you (https://generic.tools/downloads/custom/generic-child-remove-logo.zip).

All you have to do is install and activate it like any other theme, but make sure to leave Generic in your themes folder as well.

Learn more: https://developer.wordpress.org/themes/advanced-topics/child-themes/
